### PR TITLE
Added get_timeseries to preparation.py and unit test to test_preparation.py

### PR DESCRIPTION
**Pull request by iglesias-cardinale**
## Linting
  - All parts of the code I added pass pylint. I also cleaned up preparation.py so that it scores a 10/10. there's a lot going on in test_preparation.py that I don't understand, so I cleaned it up a little bit but didn't mess with it too much since I don't want to delete something useful for somebody.

### preparation.py
  - Added get_timeseries(path) 
  >Takes input of path to json file. Returns pandas time series with the index being a datetime object and the data being the concentration of CO2 / methane. Assumes that the json file has the same format as mauna-loa-data/flask_monthly.json. 
### test_preparation.py
  - Added unit test to make sure the output timeseries has the same length (# of data points) as the input json file.

## Reviewer
  - It might make sense for @avgagliardo or @haiderabbas007  to review this as they collected the data. 

This is the first time I've changed a file that somebody else created, but I think it all works. I'm doing my PR a little early in the hopes that I can fix any problems before class tomorrow. Let me know what I can improve, thanks!

### CODE REVIEW

**Comment by haiderabbas007** [comment]
I can review this

**Comment by haiderabbas007** [comment]
Here are a few comments:

1) The docstring is comprehensive and provides a good overview of the function's purpose and output. However, it can be slightly misleading since the plotting code is not part of the function itself. You might want to remove the plotting example from the docstring or clearly indicate that the plotting part is for demonstration and is not included in the function.

2) Indexing was creating an error.
Error1

3) After fixing indexing, there was an AttributeError.

Error2

4) After fixing both, the code worked and a plot was produced.

Correct

5) However, the plot has a flat portion from 1971 to 1975. Upon inspecting the raw file, I found that the data for these 5 years was missing. It would be appropriate to start from 1976 I think? @laserlab 

image

**Comment by laserlab** [comment]
> 5. However, the plot has a flat portion from 1971 to 1975. Upon inspecting the raw file, I found that the data for these 5 years was missing. It would be appropriate to start from 1976 I think? @laserlab

@haiderabbas007 Yes exactly, since this is your data collection task please open a new PR with the corrected data file

**Comment by laserlab** [comment]
@haiderabbas007 good review, but please use the review function and approve so it can get merged and you can get homework points. @SchrodingersStruggle Otherwise just merge it so we can go on

**Review by haiderabbas007 — APPROVED** [review]

**Comment by haiderabbas007** [comment]
> > 5. However, the plot has a flat portion from 1971 to 1975. Upon inspecting the raw file, I found that the data for these 5 years was missing. It would be appropriate to start from 1976 I think? @laserlab
> 
> @haiderabbas007 Yes exactly, since this is your data collection task please open a new PR with the corrected data file

Done

**Comment by haiderabbas007** [comment]
> @haiderabbas007 good review, but please use the review function and approve so it can get merged and you can get homework points. @SchrodingersStruggle Otherwise just merge it so we can go on

Done

**Comment by iglesias-cardinale** [comment]
Thank you for the review. I'll make the changes you mentioned.

**Comment by iglesias-cardinale** [comment]
I was unsure how to go about documenting the potential use of the function, so I added the example in the docstring. I agree that it could be confusing, but before looking into this I wasn't familiar with plotting using pandas so I thought the example might be useful to have. I'll remove it before class today.

**Pull request merged**
